-- database/definitions/core/aaaagg_admin/aaaakm_user_invitation_entitlements/comments.sql

-- Table Description
COMMENT ON TABLE aaaakm_user_invitation_entitlements IS 'Stores the rights granted to specific users to invite peers. Acting as a quota ledger or "gas tank" for referrals. AI CONTEXT: Separates the *right* to invite from the *act* of inviting (aaaakk).';

-- Column Descriptions
COMMENT ON COLUMN aaaakm_user_invitation_entitlements.user_id IS 'The user who owns these invitation rights. Primary key linked to aaaaff_users.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.max_invites_allowed IS 'Total quota of peer invitations permitted for this user (the capacity of the tank).';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.current_invites_issued IS 'Counter of invitations already generated by this user. Must not exceed max_invites_allowed.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.generated_invite_ttl_seconds IS 'The Time-To-Live (in seconds) that will be applied to any invitation code this user generates.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.initial_free_months_per_invite IS 'The specific subscription incentive (free months) attached to invitations originating from this user.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.granted_by_admin_id IS 'The ID of the administrator who granted or updated these rights. Part of the identity trust lineage.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.admin_notes IS 'Internal administrative notes regarding why this specific quota was granted.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.entitlement_expires_at IS 'The hard deadline for when this user ceases to be able to generate new invitations. Requires an active admin decision (NO DEFAULT).';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.created_at IS 'Timestamp when the entitlement was first granted.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.updated_at IS 'Timestamp of the last modification to the quota or parameters. Maintained by trigger.';

-- Index Descriptions
COMMENT ON INDEX idx_aaaakm_entitlements_expiry IS 'Optimized for the daily cleanup job to quickly find expired entitlements without full table scans.';

COMMENT ON INDEX idx_aaaakm_entitlements_granted_by IS 'Admin audit lookup: Quickly find all entitlements granted by a specific administrator.';

COMMENT ON INDEX idx_aaaakm_entitlements_remaining_invites IS 'Performance index for finding active inviters. Filters out users with empty gas tanks.';

-- Policy Descriptions
COMMENT ON POLICY "Allow users to select their own entitlements" ON aaaakm_user_invitation_entitlements IS 'Allows authenticated users to read their own quota status (gas tank level).';

COMMENT ON POLICY "Deny all frontend write access to entitlements" ON aaaakm_user_invitation_entitlements IS 'Strict firewall against frontend mutations. Users cannot grant themselves invites.';

COMMENT ON POLICY "Allow service_role full access to entitlements" ON aaaakm_user_invitation_entitlements IS 'Permits the backend to manage quotas and increments.';

-- Function Descriptions
COMMENT ON FUNCTION aaaakm_prune_entitlements IS 'Daily maintenance helper. Removes the right to invite after the expiration date, but keeps "empty tank" rows valid until expiry for clear UI messaging.';