-- backend/database/definitions/core/aaaagg_admin/aaaakm_user_invitation_entitlements/comments.sql

COMMENT ON TABLE aaaakm_user_invitation_entitlements 
    IS 'Stores the rights granted to specific users to invite peers. Acting as a quota ledger or "gas tank" for referrals.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.user_id 
    IS 'The user who owns these invitation rights. Primary key linked to aaaaff_ljus_users.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.max_invites_allowed 
    IS 'Total quota of peer invitations permitted for this user (the capacity of the tank).';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.current_invites_issued 
    IS 'Counter of invitations already generated by this user. Must not exceed max_invites_allowed.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.generated_invite_ttl_seconds 
    IS 'The Time-To-Live (in seconds) that will be applied to any invitation code this user generates.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.initial_free_months_per_invite 
    IS 'The specific subscription incentive (free months) attached to invitations originating from this user.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.granted_by_admin_id 
    IS 'The ID of the administrator who granted or updated these rights. Part of the identity trust lineage.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.admin_notes 
    IS 'Internal administrative notes regarding why this specific quota was granted.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.entitlement_expires_at 
    IS 'The hard deadline for when this user ceases to be able to generate new invitations. Requires an active admin decision.';

COMMENT ON COLUMN aaaakm_user_invitation_entitlements.updated_at 
    IS 'Timestamp of the last modification to the quota or parameters. Maintained by trigger.';